(*) on cree le fichier (readyphp-prod.conf) pour ajouter le contenu suivant.

sudo nano /etc/apache2/sites-available/readyphp-prod.conf

<VirtualHost *:80>
    ServerName readyphp-prod.local
    DocumentRoot /home/admins/devs/php/prod/readyphp/web

    <Directory /home/admins/devs/php/prod/readyphp/web>
        AllowOverride All
        Options Indexes FollowSymLinks
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/readyphp_prod_error.log
    CustomLog ${APACHE_LOG_DIR}/readyphp_prod_access.log combined
</VirtualHost>

(*) on desactive le site (000-default.conf) pour ne pas avoir de conflit.

sudo a2dissite 000-default.conf

(*) on active le module (rewrite) pour permettre la réécriture d URL.

sudo a2enmod rewrite

(*) on recharge les configurations apache pour prendre en compte les modifications.

sudo systemctl reload apache2

(*) on redemarre le serveur apache pour prendre en compte les modifications.

sudo systemctl restart apache2
