repos:
  - repo: https://github.com/GitGuardian/ggshield
    rev: v1.25.0
    hooks:
      - id: ggshield
        name: Scan des secrets (GitGuardian)
        description: Empêche de committer des clés API, tokens, mots de passe
        pass_filenames: false

  - repo: local
    hooks:
      - id: readyphp-format-php
        name: Formatage du code PHP
        entry: hooks/pre-commit/readyphp-format-php.sh
        language: system
        types: [php]
        pass_filenames: false

      - id: readyphp-tests-php
        name: Tests du code PHP
        entry: hooks/pre-commit/readyphp-tests-php.sh
        language: system
        pass_filenames: false
