repos:
  - repo: local
    hooks:
      - id: readyphp-format-php
        name: Formatage du code PHP
        entry: hooks/pre-commit/readyphp-format-php.sh
        language: system
        types: [php]
        pass_filenames: false
