(*) on installe samba

sudo apt update
sudo apt install samba

(*) on modifie le fichier (smb.conf) pour ajouter la configuration du repertoire de paratage.

sudo nano /etc/samba/smb.conf

[readyphp_share]
   comment = Repertoire de partage pour le projet [readyphp]
   path = /home/admins/devs/php/dev/readyphp/share
   guest ok = no
   read only = no
   browseable = yes
   valid users = admins

(*) on cree le repertoire de paratage.
(*) on definit le proprietaire du repertoire de paratage.
(*) on definit les permissions du repertoire de paratage.

mkdir -p /home/admins/devs/php/dev/readyphp/share
ll /home/admins/devs/php/dev/readyphp
sudo chown -R admins:admins /home/admins/devs/php/dev/readyphp/share
sudo chmod 775 /home/admins/devs/php/dev/readyphp/share

(*) on ajoute l utilisateur samba
(*) on active l utilisateur samba

sudo smbpasswd -a admins
sudo smbpasswd -e admins

(*) on redemarre samba

sudo systemctl restart smbd
sudo systemctl restart nmbd

(*) on verifie le status de samba

sudo smbstatus
