(*) on modifie le fichier (ports.conf) pour ajouter le contenu suivant.

sudo nano /etc/apache2/ports.conf

Listen 80
Listen 8800

(*) on recharge les configurations apache pour prendre en compte les modifications.

sudo systemctl reload apache2

(*) on redemarre le serveur apache pour prendre en compte les modifications.

sudo systemctl restart apache2
